### PR TITLE
Using jQuery [Calendars Datepicker](http://keith-wood.name/calendarsp…

### PR DESCRIPTION
**Pull request by GerZah**
Using [jQuery Calendars Datepicker](http://keith-wood.name/calendarspicker.html) instead of default jQuery picker

(1) Date fields can now be specified on either (current) Gregorian or (historic) Julian calendar.
(2) As dates stored in Omeka should probably be consistent (i.e. modern Gregorian), a Julian date that was just entered/selected can be converted to Gregorian.
(3) It is possible to specify either single dates or time spans.

The current version will work with either English, German, or French localization configured in config.ini.

Please note: The French i18n is incomplete, as the respective i18n terms from template.pot are still missing in fr.po / fr.mo (and will thus default to English). However, the calender sheets will show up in French due to the Calendars Datepicker i18n.

Please also note: Adding additional calendar localizations requires to add respective jquery.calendars-XX.js and jquery.calendars.picker-XX.js files to the ./views/admin/javascripts folder. If the respective JavaScript files are missing, that will inevitably lead to a load error in Omeka.

### CODE REVIEW

**Comment by GerZah** [comment]
Hi,

I know that this is a **_HUGE**_ modification. I needed Julian dates for my project, and the only way I saw to put this into reality was by replacing the standard jQuery date picker with one that actually supported different calendar types.

The whole JavaScript code is totally different from the tiny 6 lines that call the original jQuery date picker. ;-)

Please have a look and tell me what you think.

**Comment by jajm** [comment]
Hi,

Yes, this is HUGE :)
I think it is better to keep the date type simple. ElementTypes has been designed to be extensible by other plugins, so you could make your own. What do you think ?

**Comment by GerZah** [comment]
Hi,

you know, now that I've slept over it, I thought pretty much the exact 
same thing. ;-) Namely to revert Entity Types back to stock, and add my 
modified version with the different date picker and whatnot as a 
different content type, like "date2" or "dateGregJul" or something like 
that.

Question is: How would I do that? I think I saw you mentioning somewhere 
that different content types could / should be added through secondary 
plug-ins.

Unfortunately, I'm rather new to Omeka API programming; I find my way 
around inside existing plug-ins, but I have no clue whatsoever how to 
create one from scratch, let alone one that hooks into an existing one.

Do you find it in you to create a template plug-in, so somebody like me 
would only have to enter the plug-in name, specify the code type, and 
fill in the respective configuration / edit code?

Thanks!

Am 11.06.15 um 08:48 schrieb Julian Maurice:

> Hi,
> 
> Yes, this is HUGE :)
> I think it is better to keep the date type simple. ElementTypes has been
> designed to be extensible by other plugins, so you could make your own.
> What do you think ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biblibre/omeka-plugin-ElementTypes/pull/4#issuecomment-111015684.

## 

Gero Zahn, gerozahn@campus.uni-paderborn.de
University of Paderborn

**Comment by jajm** [comment]
You can look at https://github.com/biblibre/omeka-plugin-Taxonomy which is quite simple.
I have to write some doc for ElementTypes one day... :)

**Comment by GerZah** [comment]
That'd be awesome. :)

Am 11.06.15 um 11:20 schrieb Julian Maurice:

> You can look at https://github.com/biblibre/omeka-plugin-Taxonomy which
> is quite simple.
> I have to write some doc for ElementTypes one day... :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biblibre/omeka-plugin-ElementTypes/pull/4#issuecomment-111056455.

## 

Gero Zahn, gerozahn@campus.uni-paderborn.de
University of Paderborn

**Pull request closed without merging**
